# Application Name
spring.application.name=scoreminton

# Database Connection (Creates scoreminton.db in your project root)
spring.datasource.url=${jdbc:postgresql://db.rpirmysvnyeuenmlwqjj.supabase.co:5432/postgres}
spring.datasource.username=${postgres}
spring.datasource.password=${9SPbKBTgPTGBbaiB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
